{
	services.zapret.params = let
		list-general = ./lists/general.txt;
		list-google = ./lists/google.txt;
		list-exclude = ./lists/exclude.txt;

		ipset-all = ./ipsets/all.txt;
		ipset-exclude = ./ipsets/exclude.txt;

		quic-google = ./bin/quic_google.bin;

		tls-4pda = ./bin/tls_4pda.bin;
		tls-google = ./bin/tls_google.bin;
		tls-max = ./bin/tls_max.bin;

		simple = [
			"--filter-tcp=80 <HOSTLIST>"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-autottl=2"
			"--dpi-desync-fooling=md5sig"
			"--new"
			"--filter-tcp=443"
			"--dpi-desync=fake,multidisorder"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-split-pos=midsld"
			"--dpi-desync-fake-tls=0x00000000"
			"--new"
		];
		general-strategy = [
			"--filter-udp=443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fake-quic=${quic-google}"

			"--new"
			"--filter-udp=19294-19344,50000-50100"
			"--filter-l7=discord,stun"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--new"

			"--filter-udp=443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fake-quic=${quic-google}"
			"--new"
		];
		orig = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=568"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-split-seqovl-pattern=${tls-4pda}"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=568"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-split-seqovl-pattern=${tls-4pda}"
			"--new"

			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=568"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-split-seqovl-pattern=${tls-4pda}"
			"--new"
		];
		alt1 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-fakedsplit-pattern=0x00"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-fakedsplit-pattern=0x00"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-fakedsplit-pattern=0x00"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"
		];
		alt2 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=652"
			"--dpi-desync-split-pos=2"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=652"
			"--dpi-desync-split-pos=2"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=652"
			"--dpi-desync-split-pos=2"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"

			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=652"
			"--dpi-desync-split-pos=2"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"
		];
		alt3 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-autottl"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-repeats=8"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-autottl"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-repeats=8"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-autottl"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-repeats=8"
			"--new"

			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-autottl"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-repeats=8"
			"--new"
		];
		alt4 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=1000"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=1000"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=1000"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"

			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=1000"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"
		];
		alt5 = [
			"--filter-l3=ipv4"
			"--filter-tcp=443,2053,2083,2087,2096,8443"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=syndata,multidisorder"
			"--new"
		];
		alt6 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"

			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"
		];
		alt7 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-pos=2,sniext+1"
			"--dpi-desync-split-seqovl=679"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"
			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-pos=2,sniext+1"
			"--dpi-desync-split-seqovl=679"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"
			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=multisplit"
			"--dpi-desync-split-pos=2,sniext+1"
			"--dpi-desync-split-seqovl=679"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--new"
			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=syndata"
			"--new"
		];
		alt8 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=fake"
			"--dpi-desync-fake-tls-mod=none"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=2"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=fake"
			"--dpi-desync-fake-tls-mod=none"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=2"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake"
			"--dpi-desync-fake-tls-mod=none"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=2"
			"--new"

			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake"
			"--dpi-desync-fake-tls-mod=none"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=2"
			"--new"
		];
		alt9 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=hostfakesplit"
			"--dpi-desync-repeats=4"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-hostfakesplit-mod=host=ozon.ru"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=hostfakesplit"
			"--dpi-desync-repeats=4"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-hostfakesplit-mod=host=www.google.com"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=hostfakesplit"
			"--dpi-desync-repeats=4"
			"--dpi-desync-fooling=ts,md5sig"
			"--dpi-desync-hostfakesplit-mod=host=ozon.ru"
			"--new"

			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=hostfakesplit"
			"--dpi-desync-repeats=4"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-hostfakesplit-mod=host=ozon.ru"
			"--new"
		];
		alt10 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-fake-tls=${tls-4pda}"
			"--dpi-desync-fake-tls-mod=none"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-fake-tls=${tls-4pda}"
			"--dpi-desync-fake-tls-mod=none"
			"--new"

			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-fake-tls=^!"
			"--dpi-desync-fake-tls-mod=rnd,sni=www.google.com"
			"--dpi-desync-fake-tls=${tls-4pda}"
			"--dpi-desync-fake-tls-mod=none"
			"--new"
		];
		fta0 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=fake,multidisorder"
			"--dpi-desync-split-pos=1,midsld"
			"--dpi-desync-repeats=11"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-fake-tls=0x00000000"
			"--dpi-desync-fake-tls=^!"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=fake,multidisorder"
			"--dpi-desync-split-pos=1,midsld"
			"--dpi-desync-repeats=11"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-fake-tls=0x00000000"
			"--dpi-desync-fake-tls=^!"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake,multidisorder"
			"--dpi-desync-split-pos=1,midsld"
			"--dpi-desync-repeats=11"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-fake-tls=0x00000000"
			"--dpi-desync-fake-tls=^!"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"

			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake,multidisorder"
			"--dpi-desync-split-pos=1,midsld"
			"--dpi-desync-repeats=11"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-fake-tls=0x00000000"
			"--dpi-desync-fake-tls=^!"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"
		];
		fta1 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"

			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"
		];
		fta2 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"
			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"
			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"
			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com --new ^"
		];
		fta3 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-repeats=8"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-repeats=8"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-repeats=8"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"

			"--new"
			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake,multisplit"
			"--dpi-desync-split-seqovl=681"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-repeats=8"
			"--dpi-desync-split-seqovl-pattern=${tls-google}"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"
		];
		sf0 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"

			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"

			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"

			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=ts"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"
		];
		sf1 = [
			"--filter-tcp=2053,2083,2087,2096,8443"
			"--hostlist-domains=discord.media"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"
			"--filter-tcp=443"
			"--hostlist=${list-google}"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"
			"--filter-tcp=80,443"
			"--hostlist=${list-general}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"
			"--filter-tcp=80,443"
			"--ipset=${ipset-all}"
			"--hostlist-exclude=${list-exclude}"
			"--ipset-exclude=${ipset-exclude}"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=6"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-fake-tls=${tls-google}"
			"--new"
		];
	in general-strategy
		# ;
		# ++ orig;
		# ++ alt1;
		# ++ alt2;
		++ alt3;
		# ++ alt4;			# Finally fixing access to nixos.org sites (I killed whole day for this)
		# ++ alt5;
		# ++ alt6;
		# ++ alt7;
		# ++ alt8;
		# ++ alt9;			# Brokes with unfound reason
		# ++ alt10;			# Brokes with '^' in strategy parameters
		# ++ fta0;			# Same as alt10
		# ++ fta1;
		# ++ fta2;
		# ++ fta3;
		# ++ sf0;
		# ++ sf1;
}
