{
	services.zapret = {
		enable = true;

		params = [
			"--filter-udp=443 <HOSTLIST>"
			"--dpi-desync-repeats=11"
			"--new"
			"--filter-udp=19294-19344,50000-50100"
			"--filter-l7=discord,stun"
			"--dpi-desync-repeats=6"
			"--new"
			"--filter-tcp=2053,2083,2087,2096,8443 <HOSTLIST>"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"
			"--filter-tcp=443 <HOSTLIST>"
			"--ip-id=zero"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"
			"--filter-tcp=80,443 <HOSTLIST>"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
			"--new"
			"--filter-udp=443 <HOSTLIST>"
			"--dpi-desync=fake"
			"--dpi-desync-repeats=11"
			"--new"
			"--filter-tcp=80,443 <HOSTLIST>"
			"--dpi-desync=fake,fakedsplit"
			"--dpi-desync-split-pos=1"
			"--dpi-desync-fooling=badseq"
			"--dpi-desync-badseq-increment=10000000"
			"--dpi-desync-repeats=8"
			"--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com"
		];

		whitelist = [
			# Discord
			# Youtube
			# Nixos
			"cloudflare-ech.com"
			"encryptedsni.com"
			"cloudflareaccess.com"
			"cloudflareapps.com"
			"cloudflarebolt.com"
			"cloudflareclient.com"
			"cloudflareinsights.com"
			"cloudflareok.com"
			"cloudflarepartners.com"
			"cloudflareportal.com"
			"cloudflarepreview.com"
			"cloudflareresolve.com"
			"cloudflaressl.com"
			"cloudflarestatus.com"
			"cloudflarestorage.com"
			"cloudflarestream.com"
			"cloudflaretest.com"
			"dis.gd"
			"discord-attachments-uploads-prd.storage.googleapis.com"
			"discord.app"
			"discord.co"
			"discord.com"
			"discord.design"
			"discord.dev"
			"discord.gift"
			"discord.gifts"
			"discord.gg"
			"discord.media"
			"discord.new"
			"discord.store"
			"discord.status"
			"discord-activities.com"
			"discordactivities.com"
			"discordapp.com"
			"discordapp.net"
			"discordcdn.com"
			"discordmerch.com"
			"discordpartygames.com"
			"discordsays.com"
			"discordsez.com"
			"frankerfacez.com"
			"ffzap.com"
			"betterttv.net"
			"7tv.app"
			"7tv.io"
			# "wiki.nixos.org"
			# "search.nixos.org"
			# "home-manager-options.extrainx.com"
		];
	};
}
